### ISSUE TITLE
Feat - input mode

### ISSUE THREAD

**Issue by PowerUser64** [DISTRHO/Zinc#1]
Zinc is a very helpful plugin for extending the capabilities of DAWs and accomplishing things they don't always let you do by default. Similar to its goal of providing additional audio outputs to any plugin host, providing additional audio _inputs_ would also aid in performing tasks that DAWs sometimes make hard.

I understand that if Zinc were to provide a way of receiving audio from JACK, it couldn't run in hard Zinc mode. This is fine, as it would still enable more levels "DAW hacking" than are currently possible. Also, I think in most cases where this is needed, it is more important to have the input from JACK to begin with than it is to have it synced with the host audio thread.

**Comment by falkTX** [comment]
this is outside the scope of the project, and should be something handled somewhere else.
I have no intentions on working on this, as a way to set a nice and simple scope for this particular project.
sorry

**Comment by unfa** [comment]
Maybe some day we'll see Cobalt for inputs :D
